[project]
name = "fs25-aml-group-28"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "grapharna",
    "setuptools>=79.0.0",
]

[tool.uv.sources]
grapharna = { path = "RNAgrail" }
